tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: stack_icon
            field:
              mode: list
              container: assets
              restrict: true
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: stack_icon
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              max_files: 1
              folder: stack_icons
      -
        display: 'New Section'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              required: true
              validate:
                - required
title: Stack
